import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.scss";
import React from 'react';

 const roboto = Roboto({
   variable: "--font-roboto",
   weight: ['300', '400', '500', '700'],
   subsets: ['cyrillic'],
   display: 'swap',
 });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
   children,
   params: { locale }
 }: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  return (
      <html lang={locale} className={roboto.className}>
      <body>{children}</body>
      </html>
  );
}
