version: "3.9"
services:

  registry:
    image: registry:2
    container_name: feed-parser-registry
    ports:
      - "5002:5002"
    restart: always
    networks:
      - feed-parser-net

  service:
    image: ${REGISTRY:-localhost:5002}/feed-parser-service:main-1
    build:
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - registry
    networks:
      - feed-parser-net
    volumes:
      - config:/app/config
    environment:
      CONFIG_PATH: './config/local.yaml'
      INDEX_NOW_KEY: 'HnZJOup42wLcpbCJTYA1d1V7afW76gXkjBf1gXQZ9jSO0KRWyH2zRH8qnlF75w3x'
    command: './feed-parser-service'
    deploy:
      replicas: 0
      restart_policy:
        condition: on-failure

  rssfeed:
    image: ${REGISTRY:-localhost:5002}/feed-rssfeed-generator:main-1
    build:
      dockerfile: Dockerfile_rss
    restart: always
    depends_on:
      - registry
    networks:
      - feed-parser-net
    volumes:
      - static:/app/static
    command: './feed-rssfeed-generator'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  server:
    image: ${REGISTRY:-localhost:5002}/feed-parser-srv:main-1
    build:
      dockerfile: Dockerfile_srv
    ports:
      - "8011:8011"
    environment:
      SRV_PORT: 8011
    restart: always
    depends_on:
      - registry
    networks:
      - traefik-public
      - feed-parser-net
    volumes:
      - static:/app/static
    command: './feed-parser-srv'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.feed-srv.rule=Host(`rss.localhost`)
      - traefik.http.routers.feed-srv.entryPoints=http
      - traefik.http.services.feed-srv.loadBalancer.server.port=8011

  kremlin-indexer:
    image: ${REGISTRY:-localhost:5002}/feed-kremlin-indexer:main-1
    build:
      dockerfile: Dockerfile_kremlin
    depends_on:
      - registry
    volumes:
      - config:/app/config
    networks:
      - traefik-public
      - feed-parser-net
    environment:
      CONFIG_PATH: './config/kremlin/local.yaml'
    command: './feed-kremlin-indexer'
    deploy:
      replicas: 0
      restart_policy:
        condition: none

  mil-indexer:
    image: ${REGISTRY:-localhost:5002}/feed-mil-indexer:main-1
    build:
      dockerfile: Dockerfile_mil
    depends_on:
      - registry
    volumes:
      - config:/app/config
    networks:
      - feed-parser-net
    environment:
      CONFIG_PATH: './config/mil/local.yaml'
    command: './feed-mil-indexer'
    deploy:
      replicas: 0
      restart_policy:
        condition: none

  mid-indexer:
    image: ${REGISTRY:-localhost:5002}/feed-mid-indexer:main-1
    build:
      dockerfile: Dockerfile_mid
    depends_on:
      - registry
    volumes:
      - config:/app/config
    networks:
      - feed-parser-net
    environment:
      CONFIG_PATH: './config/mid/local.yaml'
    command: './feed-mid-indexer'
    deploy:
      replicas: 0
      restart_policy:
        condition: none

volumes:
  config:
  static:

networks:
  traefik-public:
    external: true
  feed-parser-net:
    name: feed-parser-net
    external: true
