version: "3.9"
services:

  service:
    image: ${REGISTRY}/feed-parser-service:${IMAGE_TAG}
    build:
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - registry
    networks:
      - feed-parser-net
    volumes:
      - config:/app/config
    environment:
      CONFIG_PATH: './config/local.yaml'
    command: './feed-parser-service'
    deploy:
      placement:
        constraints: [ node.role == manager ]
      restart_policy:
        condition: on-failure

  kremlin-indexer:
    image: ${REGISTRY}/feed-kremlin-indexer:${IMAGE_TAG}
    build:
      dockerfile: Dockerfile_kremlin
    depends_on:
      - registry
    networks:
      - feed-parser-net
    volumes:
      - config:/app/config
    environment:
      CONFIG_PATH: './config/kremlin/prod.yaml'
    command: './feed-kremlin-indexer'
    deploy:
      replicas: 0
      placement:
        constraints: [ node.role == manager ]
      restart_policy:
        condition: none


  mil-indexer:
    image: ${REGISTRY}/feed-mil-indexer:${IMAGE_TAG}
    build:
      dockerfile: Dockerfile_mil
    depends_on:
      - registry
    volumes:
      - config:/app/config
    networks:
      - feed-parser-net
    environment:
      CONFIG_PATH: './config/mil/prod.yaml'
    command: './feed-mil-indexer'
    deploy:
      replicas: 0
      placement:
        constraints: [ node.role == manager ]
      restart_policy:
        condition: none

volumes:
  config:

networks:
  traefik-public:
    external: true
  feed-parser-net:
    name: feed-parser-net
    external: true
