version: "3.9"
services:

  registry:
    image: registry:2
    container_name: feed-parser-registry
    ports:
      - "5002:5002"
    restart: always
    networks:
      - feed-parser-net

  service:
    image: ${REGISTRY:-localhost:5002}/feed-parser-service:main-1
    build:
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - registry
    networks:
      - feed-parser-net
    volumes:
      - config:/app/config
    environment:
      CONFIG_PATH: './config/local.yaml'
    command: './feed-parser-service'
    deploy:
      restart_policy:
        condition: on-failure

  kremlin-indexer:
    image: ${REGISTRY:-localhost:5002}/feed-kremlin-indexer:main-1
    build:
      dockerfile: Dockerfile_kremlin
    depends_on:
      - registry
    volumes:
      - config:/app/config
    networks:
      - feed-parser-net
    environment:
      CONFIG_PATH: './config/kremlin/local.yaml'
    command: './feed-kremlin-indexer'
    deploy:
      restart_policy:
        condition: on-failure

  mil-indexer:
    image: ${REGISTRY:-localhost:5002}/feed-mil-indexer:main-1
    build:
      dockerfile: Dockerfile_mil
    depends_on:
      - registry
    volumes:
      - config:/app/config
    networks:
      - feed-parser-net
    environment:
      CONFIG_PATH: './config/mil/local.yaml'
    command: './feed-mil-indexer'
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  config:

networks:
  traefik-public:
    external: true
  feed-parser-net:
    name: feed-parser-net
