version: "3.9"
services:

  registry:
    image: registry:2
    container_name: feed-parser-registry
    ports:
      - "5002:5002"
    restart: always
    networks:
      - feed-parser-net

  service:
    image: ${REGISTRY:-localhost:5002}/feed-parser-service:main-1
    build:
      context: service
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - registry
    networks:
      - feed-parser-net
    environment:
      CONFIG_PATH: './config/local.yaml'
    command: './feed-parser-service'
    deploy:
      restart_policy:
        condition: on-failure

networks:
  traefik-public:
    external: true
  feed-parser-net:
    name: feed-parser-net
