# syntax = docker/dockerfile:1.2
FROM golang:latest AS builder

WORKDIR /app

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

ARG INDEX_NOW_KEY
ENV INDEX_NOW_KEY=${INDEX_NOW_KEY}

RUN --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo -ldflags '-w -extldflags "-static"' -o ./feed-static-generator ./cmd/rssfeed

# 2

FROM scratch

WORKDIR /app

COPY --from=builder /app/feed-static-generator /app/feed-static-generator
COPY --from=builder /app/static /app/static
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
# Корневой сертификат удостоверяющего центра (УЦ) Минцифры
COPY --from=builder /app/certs/rootca_ssl_rsa2022.cer /etc/ssl/certs/
COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
ENV TZ=Europe/Moscow

ARG MANTICORE_INDEX
ENV MANTICORE_INDEX=${MANTICORE_INDEX}
ARG GENERATOR_DELAY
ENV GENERATOR_DELAY=${GENERATOR_DELAY}

CMD ["./feed-static-generator"]
