global:
  scrape_interval: 15s  # Как часто собирать метрики

scrape_configs:
  - job_name: 'rss_server'
    static_configs:
      - targets: ['host.docker.internal:8000']  # Адрес вашего сервера
  
  - job_name: 'feed-service-parser'
    static_configs:
      - targets: ['host.docker.internal:8080']  # Укажите IP и порт вашего сервиса