env: "prod" # Окружение - local, dev или prod
workers: 2
delay: 2s
random_delay: 2s
manticore_index: feed
entry_chan_buffer: 20
splitter:
  opt_chunk_size: 1800 # оптимальный размер фрагмента контента для поиска, на эти фрагменты будет разбит контент
  max_chunk_size: 3600 # максимальный размер фрагмента контента для поиска
parsers:
  - url: "http://kremlin.ru/events/all/feed/"
    lang: "ru"
    resource_id: 1
  - url: "http://en.kremlin.ru/events/all/feed"
    lang: "en"
    resource_id: 1
